networks:
  boilerplate-network:
    driver: bridge

services:
  db:
    image: "postgres"
    networks:
      - boilerplate-network
    container_name: node-boilerplate-postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=localhost
    ports:
      - "5432:5432"
