// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { default as UsersTable } from "./Users";

export default interface PublicSchema {
	users: UsersTable;
}
