// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely";

/** Identifier type for public.users */
export type UsersId = number & { __brand: "public.users" };

/** Represents the table public.users */
export default interface UsersTable {
	id: ColumnType<UsersId, UsersId | undefined, UsersId>;

	name: ColumnType<string | null, string | null, string | null>;

	email: ColumnType<string | null, string | null, string | null>;

	password: ColumnType<string | null, string | null, string | null>;

	createdAt: ColumnType<Date, Date | string | undefined, Date | string>;

	updatedAt: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type Users = Selectable<UsersTable>;

export type NewUsers = Insertable<UsersTable>;

export type UsersUpdate = Updateable<UsersTable>;
